### ISSUE TITLE
Delay touch doesn't delay with certain values in the template

### ISSUE THREAD

**Issue by jsfeldman** [monterail/vuelidate#117]
It seems the delayTouch example doesn't work if I use .$error to evaluate whether a class method should show up.

Here is a jsfiddle example with the issue:
https://jsfiddle.net/aoqv2xro/1/

If you open the console you can see test1 (which uses $v.text1.$error to determine whether to display the error class) is constantly being logged from the isUnique function, but test2 (which doesn't use $v.text2.$error) isn't logging anything.

They both start logging if I uncomment `{{$v}}`.

Let me know if there is any other information I can supply or if I'm misunderstanding how daleyTouch works. I apologize that the example isn't the greatest, but hopefully it gets the point across.

**Comment by Frizi** [comment]
Yeah, it's due to the fact that $error is also checking for $pending internally as a first value, which triggers validation.

https://github.com/monterail/vuelidate/blob/master/src/index.js#L71

It should definitely use $dirty as a first value to check, so validation is only ran when necessary. I'll change that.

But: It's not so much a bug of the delay, as if you simply ignore the evaluation and look at the final output, it's valid and consistent at all times. I wound't call it a bug at all really, it's simply how it is right now. Kinda edgy behaviour at times, but consistent in terms of final output.

Having `{{$v}}` in the template forces the whole validation object to be resolved on every render, which forces evaluation of all validators unconditionally. Don't do that in production. On the other hand, you should never really rely on computed value's execution order anyway (which also means validators) and those functions should always be pure.

Also, your example most probably is buggy. You probably ment to use `text2` instead of `text1` in the classes on second input :)

**Comment by jsfeldman** [comment]
Thanks for the reply and explanation! Sorry, the example I gave was poorly constructed.
The real use case I'm concerned about is if the asynchronous validation is making a call to a server (the real implementation of isUnique). I was hoping to use the delay to decrease the amount of requests being made. Instead of every key press it would just be when the delayed touch is run.
Do you think this is the right direction or is there a better way to accomplish this?

**Comment by Frizi** [comment]
@jsfeldman That's exactly why i even made this as lazy as possible in the first place. Even $each is implemented in a way that triggers revalidation only of changed array elements, which is unusual if you look at how Vue treats observable arrays. All of that is exactly done with promises in mind, so your point is perfectly valid and I'm going to fix this behaviour. Also, your second input works as expected if you change it's validation to `text2` :)

Thank you for that request and example!

**Comment by dsl101** [comment]
Sorry to reopen this—do let me know if you'd prefer a new issue—but I think it's very closely related. I just spent a day trying to figure out what was preventing my async validation being throttled, and it was attempting to display to the user that something was in progress. I had a component in the template which used a computed property like this:
```
signupHelper () {
    return this.$v.signupCode.$pending ? 'Checking code...' : ''
}
```
but my async check was being triggered on every input event. Is accessing `$pending` having the same 'too eager validation evaluation' effect? Guarding it like this does avoid the repeated trigger and let the throttle work as expected:
```
signupHelper () {
    return this.$v.signupCode.$dirty && this.$v.signupCode.$pending ? 'Checking code...' : ''
}
```

**Comment by dsl101** [comment]
In fact, I've ended up with the following validation, and status, which seems like it shouldn't happen:
```
    validations: {
      editedEventData: {
        name: {
          required,
          minLength: minLength(1),
          maxLength: maxLength(20)
        }, 
        signupCode: {
          minLength: minLength(2),
          maxLength: maxLength(20),
          alphaDash: withParams({type: 'alphaDash'}, v => /^[a-zA-Z0-9-]*$/.test(v)),
          async isUnique (value) {
            if (!this.checkingCode) {  // $touch triggers us, so check we really need to validate the code
              return this.codeUnique
            }
            const response = await fetch(fbConfig.functionURL + 'validateCode?code=' + value, {
              headers: {
                'Authorization': 'Bearer ' + this.user.token
              }
            })
            this.codeUnique = response.status === 200
            console.log('→', response, ':', this.codeUnique)
            this.checkingCode = false
            return this.codeUnique
          }
        }
      }
    },
```
and then in the template I've get these values (to see what's going on):
```
$v.editedEventData.$error: false
$v.editedEventData.signupCode.$error: true
```
I thought the 'higher level' validation on `editedEventData` should be the logical OR of all it's elements. But in this scenario, I end up with the `signupCode` being true, and yet the parent false.
