### ISSUE TITLE
Easy ways to locate invalid fields and DOM elements in the $v object?

### ISSUE THREAD

**Issue by wdews** [monterail/vuelidate#154]
Currently, it appears the only way to observe the `$v` object in a Vue component and understand what fields have validation is to do something like this (which feels extremely hacky):

`const validatedFields = Object.keys($v.$params).map(fieldName => $v[fieldName]);`

Then, to get a list of those which are truly invalid:

`const errorFields = validatedFields.filter(field => field.$invalid);`

Even after figuring that part out, there's no apparent way to tie validated field DOM elements to Vuelidate's `$v` object so that errors can be scrolled to in an effort to bring the user's attention straight to them.

Any suggestions on this? Thanks!

**Comment by Frizi** [comment]
Vuelidate binds itself to the model and you don't even have to validate input fields really, it can be anything. Because of that, there is no mapping to the DOM nodes whatsoever. You have to do it yourself and there are many ways to do it. You could create a directive for that or directly use `ref` attribute with field name.

Currently to get the list of invalid fields (at one nesting level), you can do
```javascript
const invalidFields = Object.keys($v.$params)
  .filter(fieldName => $v[fieldName].$invalid);
```
Later something similar to `$flattenParams` will do this work for you. If you have any suggestions how could it look like, check out #149 .

**Comment by raphox** [comment]
To help others:

```jade
form(@submit.prevent='save')
//...
.uk-margin
  input.uk-input(type='password' placeholder='Senha atual' ref='password'
    v-model.trim='object.password'
    @input="$v.object.password.$touch()"
    :class='{ "uk-form-danger": $v.object.password.$error }')
  ul.uk-list.uk-margin-remove-top.uk-text-danger(v-if='$v.object.password.$error')
    li(v-if='!$v.object.password.required')
      | Campo obrigatório
    li(v-if="!$v.object.password.minLength")
      | Deve ter no mínimo {{$v.object.password.$params.minLength.min}} letras ou números.
```

```javascript
import _ from 'lodash'
...
export default {
  name: 'page-my-profile',
  data () {
    return {
      object: {
        password: '',
        passwordConfirm: '',
        passwordNew: ''
      }
    }
  },
...
  methods: {
    save () {
      this.$v.$touch()
      const invalidField = _.findKey(this.$v.object.$params, (value, key) => this.$v.object[key].$invalid)

      if (invalidField) {
        // Using input's `ref` attribute
        this.$refs[invalidField].focus()
      } else if (this.profile && this.profile.$key) {
        this.$store.dispatch('profile/updateProfile')
      }
    }
  },
```
Referer #149
