### ISSUE TITLE
Cascading $touch()?

### ISSUE THREAD

**Issue by pohnean** [monterail/vuelidate#16]
I think it makes sense if $touching a child property also cascades to its parent properties?

**Comment by Frizi** [comment]
It's actually done the other way around. $touch always cascades to children, so you can use it on form submit event.

On the other hand, $dirty value is computed based on children too. If all children have $dirty flag set to true, parent also becomes $dirty.
Think about a whole form. You don't want to immediately notify that the whole form is invalid, when user just started typing in the first field. Once you go through all of them and left an error behind, the form will also become "red".

**Comment by mmieluch** [comment]
I disagree with @Frizi. I believe there should be another property for that, namely `$submitted`, that would be set on the form when the user _attempts_ to submit. In my opinion if a single field is invalid, therefore it makes the entire form invalid, as one should not be able to submit a form as long as there are _any_ invalid fields.

I think @pohnean is right, and that touching a child property should bubble up.

**Comment by Frizi** [comment]
@mmieluch `$invalid` property is cascaded as you just described. If a form field is invalid, whole form becomes invalid.

I'm not sure if adding `$submitted` would bring any value, especially because we don't operate on real DOM forms. You would have to remember to hook up another event by hand.

For submits, you just have to call `$touch()` on the whole validation group (be it nested or array, works anyway). This will mark every field and the group  as `$dirty` immediately. It will trigger `$error` properties on all `$invalid` validators in the group (`$error = $invalid && $dirty`). You can revert that action by calling `$reset()` on the same object. This feature essentially doubles as your `$submitted`.

Is there any use case I'm missing?

**Comment by shentao** [comment]
@mmieluch I have to agree with @Frizi on this. 

Vuelidate isn’t built just for regular forms and we try to stay away from DOM nodes. If you need a `submitted` value you can provide one yourself and set it to true on click or form submit, and then combine it with vuelidate’s `$invalid`, `$dirty` or `$error` property to accomplish the desired `$submitted` result.

Also `$dirty` can actually fill the role of `$touched` or `$submitted` depending on the event you use to trigger the `$touch()` method and the object you `$touch()`. 

Think `@blur` vs `@change` / `from.$touch()` vs `field.$touch`.

**Comment by mmieluch** [comment]
@Frizi @shentao Fair enough guys, that's some good info you're giving me here. I'm all good now and clearly need to spend some more time with __Vuelidate__. Cheers!

**Comment by shentao** [comment]
Happy to hear that @mmieluch! Hope you like it 😃
