### ISSUE TITLE
Validate Vue-multiselect

### ISSUE THREAD

**Issue by iulian34** [monterail/vuelidate#191]
Hello, 
Any possibility to use this validation with Vue-multiselect  https://github.com/monterail/vue-multiselect ?

**Comment by iulian34** [comment]
I have found the why to validate.

**Comment by IDontKnowMyUsername** [comment]
It sounds likes you figured out how to validate.  Can you give a JSFiddle example in case other people search for the same thing?

**Comment by Frizi** [comment]
You have to use exactly the same approach as with any other component. Decide on which event you want to call `$dirty`, where to put the model that goes out of multiselect and create validation on it. The difference is that multiselect can have multiple values, so you validate an array instead of string. Builtin validators support that out of the box. If you want to additionaly validate every single selected value/tag, you can use `$each` feature for that.

**Comment by Konafets** [comment]
@Frizi Can you add an example to the documenation here or at vue-multiselect?
