### ISSUE TITLE
Update documentation on custom validators

### ISSUE THREAD

**Issue by Fohlen** [monterail/vuelidate#193]
Currently a custom validators should follow ES6 and there's not much documentation or an example about it.

Here is the `maxLength` thing as an external custom validator

```js
import {req, len} from 'vuelidate/lib/validators/common'
import {withParams} from 'vuelidate'

export default length => withParams(
    { type: 'maxLength', max: length },
    value => !req(value) || len(value) <= length
)

// then where you want to use it
import maxLength from ./maxLength
```

Please add/enhance the documentation on this matter.

**Comment by Frizi** [comment]
👍  I can clearly see the docs are missing some depth here.

How do you imagine an example for that? I'm thinking about a "boilerplate validator" that you can tweak to change the code slightly. Not sure if that's enough though.

**Comment by Fohlen** [comment]
Probably that's sufficient.

**Comment by bbrewder** [comment]
It would be nice to start with the most basic possible functioning validator. Perhaps just validate that a value equals 'hello world!', or something stupid like that. Get rid of anything that isn't absolutely necessary for this to work. Then introduce parameterized validators and any other advanced topics. 

I'm trying to figure out how to do something basic (a regex, though the actual expression needs to be passed in from a server-side setting). I'm sure I'll figure it out soon enough, but it is always nice to start with a basic example, then progress to more complex examples.

**Comment by kevintruby** [comment]
I found this thread while trying to understand how to write a common validator module for several Vue components that will check password complexity, and the sample from OP was useful for figuring out how to export one.

Since I'm not trying to extend an existing module (_that i know of_), I ended up producing a simple 'hello world' evaluator to get things started. In the hopes it helps, judging from the comment above, here's what I wrote:

`// ./customValidators/stringHelloWorldChecker.js
export default text_entry => {
    return ('hello world' === text_entry);
};

// then where you want to use it
import stringHelloWorldChecker from ./customValidators/stringHelloWorldChecker`

validations: {
  someTextInputModel: { required, stringHelloWorldChecker }
}

**Comment by kevintruby** [comment]
And just to contribute a simple implementation for evaluating password complexity ;)

```JavaScript
// ./customValidators/passwordComplexity.js
export default password => {
    // probably already handled by the required flag
    if(_.isNull(password) || !_.isString(password) || _.isEmpty(password))
        return false;

    // Minimum of 1 Uppercase Letter
    if(false === /[A-Z]/.test(password))
        return false;

    // Minimum of 1 Number
    if(false === /\d/.test(password))
        return false;

    // Minimum of 6 Characters
    // separately targeting input length to provide specific error message

    return true;
};

// then where you want to use it
import { required, minLength } from 'vuelidate/lib/validators';
import passwordComplexity from ./customValidators/passwordComplexity`

validations: {
  someTextInputModel: { required, minLength: minLength(6), passwordComplexity }
}
```

**Comment by Robula** [comment]
@kevintruby Thank you for providing an example of a true custom validator. I am confused at the documentation/example that shows the use of `withParams`, it's not clear why I should use it and what `type` means in context.
