### ISSUE TITLE
requiredIf/requiredUnless doesn't work with computed properties

### ISSUE THREAD

**Issue by mr-july** [monterail/vuelidate#198]
In the example under https://monterail.github.io/vuelidate/#sub-builtin-validators is demonstrated the usage of ``requiredUnless`` with computed property.

In my fiddle (https://jsfiddle.net/mr_july/L1nv2fg6/2/) I'm trying to do the same thing, but it doesn't work. :-(

**Comment by Frizi** [comment]
This is because computed values are on root level of your component, while your property is inside a fieldset (path `object.text` has a dot). Ordinary string "locator", as used by `requiredIf` looks for sibling properties. Check the documentation of **Locator** under this documentation section you just linked.

In short, try `requiredUnless(function() { return this.isOptional })`

**Comment by dobromir-hristov** [comment]
If the `requiredIf` validator has access to the main scope, could we have like a setting as a second parameter `{root: true}` or something like that? This would make simple validations a bit easier.
