### ISSUE TITLE
Support circular validation structure and/or data?

### ISSUE THREAD

**Issue by mokkabonna** [monterail/vuelidate#210]
Any chance of supporting circular validators? I think it should be possible, just need to make sure to stop traversing the tree when you find a previously encountered validator object. And the $v data property needs to be only created as far as there are matching data to actually validate, maybe one level deeper or something like that.

```js
var vm = new Vue({
  el: "#app",
  data: {
    person: {
      name: 'John'
    }
  },
  validations: function() {
    var personValidators = {
      name: {
        required
      }
    }

    personValidators.bestFriend = personValidators

    return {
      person: personValidators
    }
  }
})

var john = vm.person

var peter =  {
  name: 'Peter',
  bestFriend: john
}

john.bestFriend = peter
```

This example demonstrates both circular validators and circular data. Maybe circular data is a bigger problem to support. This might not be at the top of your priority list, but just asking if you think it's at all possible. :)

This would give you `vm.$v.person.bestfriend.bestfriend.bestfriend.bestfriend.etc..`

I encountered this when exploring supporting circular refs from json schema. https://github.com/mokkabonna/vue-vuelidate-jsonschema

The ability to create circular validation structure would be nice, then I could build something like the data structure of a filesystem tree with similarily validated nodes, with unlimited depth. With only a core set of validation object.

Supporting circular data is not that important for me.

**Comment by Frizi** [comment]
Usually vuelidate mimics the shape of data, so I'd say to even talk about circular validations in traditional sense, we need circular data in the first place.

Relaxing that a bit and speaking of possibilities though, vuelidate already violates that in one place - validation groups. 
And it's kinda possible to create circular validation with them already: https://jsfiddle.net/b5v4faqf/381/ :D

But it's not practically useful.  This validator is never going to be valid, as it's children (including itself) will never all be valid. Also doing `$v.$touch()` is going to overflow the stack. I would rather not do that.

I think what you need is dynamic validation shape based on potentially circular data, as JSON schema defines. It never really deals with dynamic circular references, because the JSON format itself doesn't allow them. It's only an arbitrarily deep self referencing type we are talking about, but it has to have a limit.

And for that problem I think there is already a solution. Nothing prevents you from snooping the actual data by yourself in `validations` function. In fact, I've done it a few times in different examples across issues. See this one: https://github.com/monterail/vuelidate/issues/166.

You can do the same by starting off from your data tree and matching the JSON schema types based on traversed paths, leaving a tree of validators behind.

**Comment by mokkabonna** [comment]
Hmm you are right, I think I attacked this a bit wrong. I just need to regenerate the validations whenever new levels are added.

Thanks for the feedback!

**Comment by mokkabonna** [comment]
Have a basic implementation here https://github.com/mokkabonna/vue-vuelidate-jsonschema/pull/9

At least work with the most basic circular structure, as long as I add data objects new validations are added. https://github.com/mokkabonna/vue-vuelidate-jsonschema/pull/9/files#diff-ab18e01eddc6a5b8d03740b166d687a4R106

**Comment by Frizi** [comment]
You don't necessarily have cache anything though, as validators are resolved similarly to vue's `render` function. A virtual validation tree is created, compared and only changes are applied. That means you can simplify that to the bone on your side, simply making validations a computed of schema and data without any extra internal state.

I think you are mostly doing it, but I see that you still try to compute it based on schema first, only then detecting circular types and treating them separately. What you could do instead is to always traverse the data tree instead. It could be much simpler and I believe it will still be pretty fast.
