### ISSUE TITLE
Validating specific inputs in a custom component.

### ISSUE THREAD

**Issue by shihaotan91** [monterail/vuelidate#235]
I have a InputHelper that is supposed to a wrapper to various custom form components. In InputHelper I import those forms and use them like this.

```
<template>
        <input-action v-if="inputField == 'action'":entities="entityList"></input-action>
        <input-trigger v-else-if="inputField == 'trigger'"></input-trigger>
        <input-skill v-else-if="inputField == 'skills'"></input-skill>
</template>

<script>
        import Action from '@/intents/client/views/components/Action.vue';
        import Trigger from '@/intents/client/views/components/Trigger.vue';
        import Skill from '@/intents/client/views/components/Skill.vue';
</script>
```

In another component called Form.vue, I import InputHelper and render the forms I want by passing props to them.

```
<input-helper slot="form" ref="actionView" inputField="action"></input-helper>
<input-helper inputField="trigger" slot="form" ></input-helper>
<input-helper inputField="skills" slot="form" ref="skillsView"></input-helper>
```

Each form is a huge component with many input html elements to them. Snippet of Trigger form.

```
<form ref="newRecordForm" class="row px-5 py-3 record-item" autocomplete="off" @submit.prevent="$event.preventDefault();">
            <input type="text" placeholder="Type new Trigger 1 here" class="col col-md" id="add-new-trigger1" v-model="newRecord.name1"/>
            <input type="text" placeholder="Type new Trigger 2 here" class="col col-md" id="add-new-trigger2" v-model="newRecord.name2"/>
            <div class="col col-md-2">
                <button class="btn pmp-round-add" @click="this.onAddTrigger"></button>
            </div>
</form>
```

Is is possible for me to use vuelidate at the InputHelper wrapper or Form.vue to validate a specific input at the individual forms? For example, make sure that Trigger 1 fields is required but not Trigger 2 upon clicking the `pmp-round-add button`. However, I want to do this without adding any new code in the Trigger component, just the InputHelper wrapper or Form.vue.

Appreciate the help!

**Comment by Frizi** [comment]
There are many ways to do it. Usually you want to define your `validations` at the form stage, thus in your "Form.vue". The rest is really a matter of taste.
It all depends on where you want to display the error and call `$touch`. If you'd like to show errors as part of input-helper component, then you can just pass the part of validation as a prop alongside the model. If you prefer to do all the validation at the form level (instead of in each field), then you would simply use the created validation object directly as part of your form template, without ever passing it down to form components.
