### ISSUE TITLE
Get first error

### ISSUE THREAD

**Issue by pohnean** [monterail/vuelidate#24]
I think there should be a method to get the first error of an attribute. Right now it is very inconvenient to do so.

**Comment by Frizi** [comment]
What do you mean by first? Validators are objects, there is no inherent order.

It's convenient once you define such order by yourself and put your error messages into a component, but there is no single right way too do it. It depends on your requirements heavily.

Do you have any specific example in mind?

**Comment by mubaidr** [comment]
I have written a function that returns list of error messages for each validation specified in the validations. This makes it easy to display validation summary by using vue binding and computed methods.

**Comment by Frizi** [comment]
@mubaidr Go on, I'd like to see that very much :) we planned something like that eventually, but it's still only in our heads. Thanks in advance :)

**Comment by mubaidr** [comment]
Great! I will do it.

**Comment by mubaidr** [comment]
I have created a small helper function, it is not complete yet, but will be good as as a starting point: https://github.com/mubaidr/vuelidate-summary

**Comment by Frizi** [comment]
Nice concept :) Let's try get rid of the potential flaws.

1. AFAIK you are keying by label instead of by function name now. That's perfectly OK, but we have to somehow allow library users to specify their own label. This hints a need for configuration. Current approach for anything like that was to favour local configuration instead of anything global.

how about something like:
```javascript
const myMessages = {
  required: '{field} is required.',
  alphaNum: '{field} can only contain alpha-numeric characters.',
  sameAs: '{field} must be same as {otherField}',
  minLength: '{field} must contain at least {minLength} chartacters',
  minLength6: () => myMessages.minLength // alias 
}

... 
{ validationSummary: Summary(myMessages) }
```

2. Maybe we should use a kind of visaully "resered" word here? That way it's obvious we are not actually validating the field. Think `$each` or `$trackBy`. I'm thinking about eventually having that in the core if footprint will be small enough, and then that's the obvious way to do it for me.
```
$summary: Summary(myMessage)
```

3. What about translations? Not all libraries prefer to get the translated messages as a bunch of strings, so I imagine we would have to use translation keys instead. Problem shifts to the template usage point then and we still have to provide a **predictible** set of parameter names.

I unfortunately don't have any specific solution there yet.

**Comment by mubaidr** [comment]
I will be working on this to improve and your feedback will be required much! 👍 1,2 seems pretty clear, I will continue work to try and add ability to provide custom (& optional) messages for any validation function. 
but i have never used translation keys (not even translation messages), will try to grasp the concept of translations. 

BTW, just a request, can we have documentation/comments in the code to better understand the working, especially for new users/contributers. thanks

**Comment by Frizi** [comment]
The code highly relies on the way how Vue computed values works, so you have to grasp that one first. Think a tree of components with computed values based on your model, but which it's values accessible under a $v attribute. Async validators feature brings some more comments to the code too.

About third point, check out how `vue-intl` and `react-intl` works. The fist one still misses a feature of using components as a translated messages, but I use similar concept in my code and maybe i'll contribute it soon. It's important, because it let's you put any html (including components) as a translation parameter without treating whole translation strings as html. We can have XSS otherwise if translation source cannot be trusted.

This approach requires you to not treat your translations as strings, but as a VDom nodes instead. That's hard in vue, but doeable in templates using slots. It's a reason to push the translations and messages down do template in a component, probably a user made one, so we don't bind to any specific library. We might have a few binders as a separete modules though.

**Comment by ctf0** [comment]
@Frizi for the translation, we can

1- add a default english summery messages and a new key that gets passed to the validation instance like

```js
import Vuelidate from 'vuelidate'
Vue.use(Vuelidate)

new Vuelidate({
  locale: 'en'
});
```

* or we can have it inside the validations object to make it easier for the user to change it by other methods

```js
export default {
  data () {
    return {
      name: '',
      age: 0
    }
  },
  validations: {
    locale: 'en',
    name: {...},
    age: {...}
  }
}
```

* and if the user wants to override the default messages then we can have like a special key `$messages` that does that

```js
export default {
  data () {
    return {
      name: '',
      age: 0
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4),
      $messages: [
	  {required: 'the name is required and cant be empty'},
          {minLength: 'the name have to be at least 4 charachters'}
      ]
    },
   // ...
  }
}
```

2- make another package to only hold the messages for the other locales, which allow the user to just change the `locale` value and get the new translated messages.

**Comment by Frizi** [comment]
@ctf0 this issue is discussed in closer details in #3. Many of the arguments against storing strings in validations or referencing the errors are already presented there.
