### ISSUE TITLE
Can't seem to get maxValue working with date

### ISSUE THREAD

**Issue by molerat619** [monterail/vuelidate#266]
I tried to use maxValue with dates in so many different way, but I can't seem to get it to work.

Here is my fiddle with one version: https://jsfiddle.net/b5v4faqf/1160/

I have tried using moment.js, passing the date as YYYY-MM-DD string or as real date, using `maxValue: maxValue(-thedate-)` and `maxValue: -thedate-` and various combinations.

What is the right way to do it? I need to make sure the entered date is in the past or today.

**Comment by Morgul** [comment]
I'm having exactly the same problem.

**Comment by somazx** [comment]
Looking at the source maxValue expects the two compared values to be instances of Date.

In my case the model value was a string and I already had moment js as a dependency so I wrote my own:


    ....
    validations: {
        date_field: {
            notInFuture: (date_field) => moment(date_field).isSameOrBefore()
        }
        ...

**Comment by Frizi** [comment]
This is tricky. `maxValue` correctly compares two date objects, but the problem is your date input. Unfortunately, HTML date operates on dates in `YYYY-MM-DD` string formatting.
You could use computed values to do initial formatting and validate it instead. Check this example:

https://jsfiddle.net/Frizi/b5v4faqf/2889/

**Comment by Burstaholic** [comment]
It's a little weird that making it a string on both sides still fails to compare correctly.
