### ISSUE TITLE
Message Params

### ISSUE THREAD

**Issue by shentao** [monterail/vuelidate#3]
```
name: {
  required,
  minLength: minLength(6)
  maxLength: withMessage(maxLength, 10)
}

function withMessage (rule, ...args) {
  const wrapRule = rule(...args)
  wrapRule.messageParams = () => args
  return wrapRule
}

function required (x) {
  return !!x
}

required.messageParams (x) {
  return
}
```

**Comment by mubaidr** [comment]
While now, the validator functions returns only boolean values, what if we make it return an object like this: 
`
return {valid: true|false, options}
`

While the options object is passed when validator is assigned to inputs. like: 
`
email: {
          required: required({
message: 'Email field is required!'
         }) || null
          email,
          minLength: minLength(6),
sameAs: sameAs({
message: 'Email should be same as username!'
})
        }
`

What i am proposing is that, we just return the options object as it is from validation function to vuelidate. This way we might use to add more options in the future. Like, validation summaries and automatically adding error messages to inputs. This will still keep it easy to write to own custom validation functions but just adding options method. 
I am new to this mvvm pattern, so pls excuse me if i am wrong and missing something.

Sample validation function:
`
export default {value, message} => {
  let reg = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/
  return {isValid: reg.test(value), message: message}
}
`

Obviously it will require to modify vuelidate heavily (i think so), but i think it will payoff, unless i have mis-understood something.

**Comment by Frizi** [comment]
No need for heavy modifications, but treating arbitrary objects with `value` key is dangerous once you allow any functions as an input. It's a gotcha. What i though about before is to extend the rule function alone with additional field. It's much harder to collide, as not many random libraries are sharing this approach. Trick is we can't rely on the fact that input functions are unique, or we would end up in overwriting the params with multiple invocations. We have to wrap them anyway to create a new reference.

Still, this is just an implementation detail. We have to focus on the API first, think about what's easy to use and don't have surprising consequences. Later we can think how to accomplish that.

I would like to keep the validator interface as it is:
1) For promises, treat as async validator
2) For functions returning vuelidate instances (think validation groups), use those directly
2) for anything else, coerce to boolean.

**Comment by sqal** [comment]
@Frizi Just want to throw an idea. I know you've said:

"I would like to keep the validator interface as it is"

but would it be bad if we would do something along these lines:

```
validations: {
  name: {
    rules: {
      required,
      minLength: minLength(4)
    },
    messages: {
      required: 'Field is required',
      minLength: 'Name is too short' // or it can be a function(?)
    },
  }
}
``` 

and the result model:

```
name: {
  "required": true,
  "minLength": false,
  "$invalid": true,
  "$dirty": true,
  "$error": true,
  "$pending": false,
  "$errors": [
    {
      "message": "Name is too short",
      "rule": "minLength"
    }
  ]
}
```

Also would be nice if we could specify somewhere global messages e.g for required validator, if user doesn't provide one in the `messages` object. I especially would really like to see this `$errors` field where I have an array with all my error messages, because i can then easily pass this array to some component which would render a nice list for me :) it  would come in handy in the following scenario:

```
<div v-for="field in fields">
  <ui-textfield v-model="field[model]"></ui-textfield>
  <form-errors :errors="$v[field.model].$errors"></form-errors>
</div>
```

I think this would be just perfect. Currently In my app i implemented similar solution but is very hacky atm and not that flexible as i would like it to be :/ So, that's my two cents. Let me 
 as i would like it to be. Let me know what you think :)

**Comment by johnnynotsolucky** [comment]
Would it be suitable to extend validators to include a `message` function, you can then map these functions as computed properties to the internal VM.

A validator could look like:

```
import required from './required'

export default (min, max) => {
  const validator = value => {
    return !required(value) || (!/\s/.test(value) && Number(min) <= value && Number(max) >= value)
  }
  validator.message = value => ({ min, max, current: value })
  return validator
}
```

Map the message functions the same way as you do the validator functions, just don't include them in the proxy VM. A computed `$msg` property can return the results.

```
repeatPassword: {
  "sameAsPassword": true,
  "$invalid": false,
  "$dirty": false,
  "$error": false,
  "$pending": false,
  "$msg": {
    "min": 20,
    "max": 30,
    "current": 42
  }
}
````

Working changes: johnnynotsolucky/vuelidate@d5306bd28813a96f732cf6d6ae847d354accc7c3

**Comment by jrenton** [comment]
We are currently upgrading to Vue 2.0 and `vue-validator` is the hangup we are dealing with. Investigating `Vuelidate`, this issues (having a message) seems to be the missing piece to easily replace what we have. I started down a path with changing `Vuelidate` to do this, and thought about having a syntax similar to:

```
{
  age: {
    $rule: required,
    message: 'Age is required!'
  }
}
```

This would cause minimal change to existing functionality because basically any object that contains `$rule` is a "validateable" object via `$rule`, where `$rule` just represents exactly what validators expect right now.

I'm not sure exactly how the inner workings of `Vuelidate` works (exploring it now), but then using each `$rule` object's message this can output a recursive `$errors` array similar to how all other properties work with output looking like:

```
$v: {
  "age": {
    "$invalid": true,
    "$dirty": true,
    "$error": true,
    "$pending": false,
    "$errors": ["Age is required!"]
  },
  "$invalid": true,
  "$dirty": true,
  "$error": true,
  "$pending": false,
  "$errors": [{
    "field": "age",
    "message": "Age is required!"
  }]
}
```

**Comment by shentao** [comment]
@jrenton This looks pretty much as the solution I created for my project that became a loose inspiration to Vuelidate later on.

I guess it would be helpful to add support for messages as functions bound to the component context, so they can make use of the currently validated value (or any others), giving us something similar to message params.
@Frizi wdyt?

@johnnynotsolucky Rather than extending the validators I would look for a wrapper `withMessage` function that when called, would pass the args to the validation function and return the message and validation results as an object. After this, all we had to do would be checking if the returned value is a Boolean or an Object. However this approach might make it harder to create a collective `$errors` array.

**Comment by Gr33nbl00d** [comment]
This is exactly what i would like to see :) I created a different issue which more or less contains some of your ideas, the issue name was a bit irretating for me so i didnt see this issue till know.
could you have also a look on my issue too:
distinguish between validation rule and validator

**Comment by johnnynotsolucky** [comment]
@shentao A wrapper makes much more sense. Are you leaning more towards returning parameters passed to the validation function as apposed to a validation message? A model like what @Frizi illustrated in the second comment of this thread:

```
name: {
  required: true,
  minLength: false,
  $invalid: true,
  $dirty: true,
  $error: true,
  $msg: {
    minLength: {min: 8, current: 3}
  }
}
```

It seems like this would be the desired result; it keeps the plugin decoupled from the template, and strings out of the javascript.

**Comment by Frizi** [comment]
@jrenton @shentao I really like the idea and I'm aware we have to somehow adress that, but I'm still very cautious about putting the strings into the rules. It's just the fact that strings/i18n belong mostly to the view, not to the model/logic (which is kind of where validation is). I really do like the idea of exposing necessary message data with the validation model, which leads to next proposition.

@johnnynotsolucky This solution is pretty good, but it falls down when we want to keep validators just as a simple functions. We can just treat that as an opt-in though. Javascript being javascript, we can assign extra fields to the functions alone, as function is just a fancy callable object (heck, flow even supports typing that, but that's for another discussion).

Second of my concerns is that functional composition will destroy this. Think of `or` and `and` validators. Possible solution is to nest those, which increases complexity. But, in the end of the day, better done than perfect.

So, proposal:

We can specify validators like usual, but adding extra lines to assign passed values:
```javascript
const minLength = (min) => {
  const validator = (value) => value.length >= min // simplified
  validator.$params = { type: 'minLength', min } // expose passed min value
}
```

This kinda drops the support for proposed `current` value, but I'm thinking it's utility is marginal anyway, and you can always grab it from data directly if needed.

You could just use the validator as usual:
```javascript
validations: {
  field: {
    minLength: minLength(10),
    maxLength: maxLength(20),
    required,
    // as a nested validator is just another kind of validator,
    // it could even specify it's own $params, because why not
    $params: { awesome: 'parameter' }
  }
}
```

Now, Vuelidate can check if there exists a `$params` key on exposed validator function, and make use of it exposing it further.

```javascript
$v: {
  "field": {
    "minLength": false,
    "maxLength": true,
    "$invalid": true,
    "$dirty": true,
    "$error": true,
    "$pending": false,
    "$params": {
      "minLength": { "type": "minLength", "min": 10 },
      "maxLength": { "type": "maxLength", "max": 20 },
      "required": null
    }
  },
  "$invalid": true,
  "$dirty": true,
  "$error": true,
  "$pending": false,
  "$params": {
    // if it weren't for $params in the field, it would be null but still defined
    "field": { "awesome": "parameter" }
  }
}
```

Now, `$params` knows nothing about the validation state of any particular validator, it just exists. It always contains the keys to all validators, having nulls for ones that specifies nothing. It allows for pretty easy tree traversal without tracking too many things. There are no arrays in the process, so any specific order is up to the user, as it always was.

Pros:
 - expands API area only minimally, adding only one more reserved keyword
 - no translations in data - it stays in the view
 - opt-in - no hassle if you aren't gonna use it
 - compatible in any level, will just work with nesting or arrays
 - every single validation level contains only and all data only about itself, you can still pass $v alongside with the data to your form components
 - no added preferable order - unordered sets of fields stays unordered, it's up to the user
 - no global configuration
Cons:
 - it really needs extra components and utilities for tree traversal
 - ???

Next step:
get rid of the con, ship with default implementation of error collection tree traversal

I imagine it like:
```html
<ShowError v-for="error in $v.collectAllErrors(myPreferredOrder)", :error="error" />
```
But that's just about thinking forward, it's for another discussion.

WDYT?

**Comment by Gr33nbl00d** [comment]
Reasons why i would move the messages from view to validation model or at least make both possible.
If you see the validation as rules only i understand why this doesnt seem to make sense, but:
If you see a composition of rules for a specific use case like for example username validation, this is something which likely needed in many different views. So to not copy these stuff i could define validators externaly which can be used in different views, no need to copy the messages. Another reason is that the text which needs to be displayed can be dynamic which could be helpfull.
Just to explain my use case i use some external translation and text management service locize.com
This way i can easy add support for new languages. This service will return a key,value map which will translate abstract key like "userNameRequiredText" to a language specific error message like "Username is required". I will anyhow just define these keys in the model not the specific text. So what would help me a way to define a text key for each validation rule and additionally a translation function which i can set to the validation model which will be used to translate the keys to translated texts.

**Comment by Frizi** [comment]
> So to not copy these stuff i could define validators externaly which can be used in different views, no need to copy the messages.

Fair enough. Use any translation library for that or define your messages elsewhere. No need to mix them into validations. We already have `import`s or language definitions for that.

> Another reason is that the text which needs to be displayed can be dynamic which could be helpfull.

That's why we have params, so you don't have to specify a translation for every possible combination of parameters. Any othetr dynamism alone or even language change should be handled by external i18n library, like `vue-intl` for example.

> i would move the messages from view to validation model or at least make both possible.

The reason i really don't want to mix strings into validations is because those are often defined outside of the application altogether, managed by external libraries or even compiled into scripts by external transpilers. Those are not really __strings__, those are __messages__, whatever it means in given context. Also there is a whole scope of problems like making a specific segments of messages bold. You don't want to put a html from external sources straight into your DOM nodes. This should be left for a specialised library. Check https://github.com/learningequality/vue-intl/issues/5 as an example.

**Comment by Gr33nbl00d** [comment]
Ok i see not all like this idea. So i created my own solution as i consider my approach nevertheless a good architecture i fixed it with some small framework. For me this problem is fixed now and im happy with my solution. For other interested this is how the code looks:

Model:

```js
    var validatorList = new ValidatorList();
    validatorList.addValidator('username', new UsernameValidator());
    validatorList.addValidator('password', new PasswordValidator());

    export default {
      data() {
          return {validationList:validationList, username:"", password:""}
        },
      validations : validatorList
    }
```

View:
```html
<div>
  <input type="text" name="username" v-model="username">
  <!-- shows first error under textfield -->
  <span>{{validatorList.getResult("username").getFirstError($v)}}
</span>

</div>
```

On mouseover i render easily a list of problems with;
```html
  <ul>
    <li v-for='item in validatorList.getResult("username").getErrors($v)'>
      {{ item }}
    </li>
</ul>
```

UsernameValidator looks like this:
```js
function UsernameValidator() {
    this.required = new DefaultRuleValidator(required, "Field is required");
    this.minLength = new DefaultRuleValidator(minLength(4), "Text must be at least 4 chars");
}
UsernameValidator.prototype = Object.create(Validator.prototype);
```
of course i could abstract DefaultRulevalidator more to RequiredRuleValodator or simply add i18n function by overriding getErrorText from Validator class, but i tried to keep it simple

**Comment by Frizi** [comment]
@Gr33nbl00d 
If you insist on holding your messages directly on validators, it's actually possible with my approach. You just have to add the parameter you will use. I'm using `withParams` function here which is currently implemented on the related branch. Playing with the idea.

Here is an example of talking your approach by using provided API:

```javascript
import {required as originalRequired} from 'vuelidate/lib/validators'
import {withParams} from 'vuelidate'

const required = withParams({msg: 'Field is required'}, orginalRequired)
```

Use this validator instead of original required, and you will be able to do this:
```html
<span class="error" v-if="$v.field.error && $v.field.required">
  {{ $v.field.$params.required.msg }}
</span>
```

or even this, to display all errors
```html
<ul class="errors" v-if="$v.field.error">
  <li v-for="(key, params) in $v.field.$params" v-if="$v.field[key]">
    {{ params && params.msg }}
  </li>
</ul>
```

If you choose to use translations, all currently defined validators already provide "type" parameter, so you can use it for your messages too.

```html
<ul class="errors" v-if="$v.field.error">
  <li v-for="(key, params) in $v.field.$params" v-if="$v.field[key]">
    <FormattedMessage :id="`validation-${params.type}` :values="params" />
  </li>
</ul>
```

for messages like that:
```yaml
validation-required: "Field is required"
validation-minlength: "Field must have at least {{min}} characters"
```

**Comment by Gr33nbl00d** [comment]
This sounds like a good option i will check it out :)

**Comment by Frizi** [comment]
I just realised there is a big con of this approach, have to work it around

```javascript
// builtin
const builtinValidator = (param) => withParams({ param }, (val) => val > param)

// custom
const myValidatorWithFilledParam = function (val) {
  return builtinValidator(this.modelValue)(val)
}
```

Custom validator loses the params in current implementation.

Playing with return value instead of "mounting" the params on the function itself would probably help resolve that issue, but it's a breaking change essentially.

**Comment by Frizi** [comment]
I managed to get around that issue, but it complicates the implementation quite significantly and adding $params to the validation objects is no longer possible. It works only with the final validator functions, actually tracking their execution at runtime. check #52

**Comment by benosman** [comment]
@Frizi 

I've read through this issue and #52, but I can't work out what the suggested approach for adding messages to validators is.

I've tried some of the examples above like using `withParams` and that works with simple validators like `required` but when using it with a validator that already uses withParams like `minLength`.

Any pointers would be gratefully received :)

**Comment by Frizi** [comment]
`withParams` adds meaningful keys to `$params` object that you are supposed to use as an input to your translation system on the view layer. For example `<div v-if="!$v.name.required">{{ translate($v.name.$params.required) }}</div>`. As $params always mimics the shape of original validations, you can also use a `v-for` to iterate over all errors and translate them. Now it's a matter of building this `translate` function that you should take care of and provide your own mesages map there. Check out existing solutions for translation support too, that was meant to be compatible with them.
