### ISSUE TITLE
Access reference models for "sameAs" validator

### ISSUE THREAD

**Issue by mubaidr** [monterail/vuelidate#30]
How can i access referenced models/names used in "sameAS"

`
password: {
          required,
          alphaNum,
          minLength: minLength(6)
        },
        confirmPassword: {
          sameAs: sameAs('password')
        }
`

I want to display a generic message on validation error that "confirmPassword" must be same as "password" (how to get this name?).

**Comment by Frizi** [comment]
As a validator is simply a higher order function, there is no way to access the arguments you passed to the validator outside of it's scope.
We were brainstorming that idea, but it's really hard to accomplish without giving up a very important feature, which is a seamless support to arbitrary functions as validators from any library.
Please check https://github.com/monterail/vuelidate/issues/3 as our latest idea how to implement a `withMessage` modificator.

Currently we lean towards just specifying your message parameters by hand.

You can prepare a translation like `Your {field} is not identical to {otherField}.` and just provide the parameters by hand like `{field: 'repeated password', otherField: 'original password'}`.
Notice that this is not even a valid translation, as translation parameters should be independent of the language, so the problem is much deeper. In the end you have to specify the whole message for each usecase anyway. We don't want to implement translations in a library with different responsibilities, so instead an external translation libraries have to be easy to use in combination with Vuelidate.

For us it was an argument to not include this feature for now, as there are many gotchas. Feel free to join the brainstorming, any input is appreciated.

**Comment by mubaidr** [comment]
Well, now i understand, thanks for the explanation. I will follow #3 to keep an eye on progress.
