### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by ghenry** [monterail/vuelidate#369]
Hi,

Is there any where else this is maintained? Doesn't seem like much activity at the moment.

Thanks.

**Comment by snaffi** [comment]
I think yes, because last commit was 11 days ago

**Comment by mikeerickson** [comment]
@ghenry Curious, why do you think it is not maintained?  As noted above, last commit was just 11 days ago?   Is there some reason to be alarmed?  I only ask because I am evaluating this project myself.

**Comment by Frizi** [comment]
Hi,
The project is hopefully still alive, but things have changed recently indeed. I am no longer able to maintain it due to the fact that I left the company i was developing it under and I no longer have the commit rights. It is supposed to be maintained by monterail, so hopefully you will see more activity from their side soon.

**Comment by thedamon** [comment]
@Frizi without hearing anything from Monterail, would it make sense to fork this? Is there interest? I personally find the data-based approach very nice and not something offered by main competitors (which is essentially vee-validate as far as I know).

**Comment by shentao** [comment]
Hey @thedamon! One of the original creators here in the same situation as @Frizi.
I think forking it might be a good call. 

I was also thinking about building a new vuelidate-like library that would get rid of some of the APIs (like `$each`) which encourage bad component design and are also the reason that makes the library unnecessarily complicated. Should make it simpler and easier to maintain.

Sadly, I can’t give an ETA, since I’m still way behind on the new vue-multiselect release. 

But if someone would like to join and help – let me know!

**Comment by thedamon** [comment]
@shentao I wish I had time and expertise to be a part of this!  I would be happy to at least be a sounding board, and help with documentation and be generally encouraging.

Are there other things specifically you would like to change or emphasize as good usage patterns in Vuelidate?

I'm currently in the midst of trying to integrate vuelidate into a design system/component library with a sort of form-builder aspect (custom inputs and form submission patterns etc), and I'm rarely sure of what I'm doing...

**Comment by shentao** [comment]
Thanks @thedamon! We’re now working on a roadmap and categorizing the issues that were reported so far. I also started working on a 2.0 rewrite, but since the library code is quite complicated, this might take a while. 
In the meantime, we would like to solve some of the bugs that are within our reach. That is, those that don’t require a major rewrite. If you’d like to help with those – let me know or just comment on an issue that you would like to work.

One of the new design ideas we have for the rewrite is to create a connection between parent and children components that contain some validation rules. This would make it possible for the ancestor to be able to track the validation state of all of its children without any additional effort from the developer. 
Putting it into a context of form-builder – you should be able to have a Form component with dynamic fields, where each field is a component and has its own validation rules and the Form component can keep track of them.

As for bad patterns – I’m strongly against using `$each`. There are usually two cases where you need it:
1) You need to validate the whole array where you want to run a rule against each element. Instead you can use Array `.some` in combination with a validator on top of the whole Array. 
2) You need a `v-for` to display elements and validation results for those elements. In that case, I think it’s better to encapsulate that `v-for` template into a new component since (that is something I recommend for Vue in general, not just validations). Having access to `$each` might discourage people from extracting that component.

**Comment by windymindy** [comment]
@shentao I really need that $each feature. Do you mind contacting me, when it is suitable for you, so I could show the case?

**Comment by shentao** [comment]
Hey @windymindy, could you please elaborate more about your use case? You can drop me an email at damian at dulisz.com

**Comment by cby016** [comment]
> Thanks @thedamon! We’re now working on a roadmap and categorizing the issues that were reported so far. I also started working on a 2.0 rewrite, but since the library code is quite complicated, this might take a while.
> In the meantime, we would like to solve some of the bugs that are within our reach. That is, those that don’t require a major rewrite. If you’d like to help with those – let me know or just comment on an issue that you would like to work.
> 
> One of the new design ideas we have for the rewrite is to create a connection between parent and children components that contain some validation rules. This would make it possible for the ancestor to be able to track the validation state of all of its children without any additional effort from the developer.
> Putting it into a context of form-builder – you should be able to have a Form component with dynamic fields, where each field is a component and has its own validation rules and the Form component can keep track of them.
> 
> As for bad patterns – I’m strongly against using `$each`. There are usually two cases where you need it:
> 
> 1. You need to validate the whole array where you want to run a rule against each element. Instead you can use Array `.some` in combination with a validator on top of the whole Array.
> 2. You need a `v-for` to display elements and validation results for those elements. In that case, I think it’s better to encapsulate that `v-for` template into a new component since (that is something I recommend for Vue in general, not just validations). Having access to `$each` might discourage people from extracting that component.

Has there been any update on this? I am currently using Vuelidate in a project and I'm wondering if there is a new version available?

**Comment by shentao** [comment]
Hey @cby016! We recently released a patch for 0.x as well as v2.0 alpha which is a complete rewrite targeting Vue 3.0 with composition-API support. It's also mostly backwards compatible. See the next branch for more details.
