### ISSUE TITLE
Support multiple validation triggers

### ISSUE THREAD

**Issue by roryprimrose** [monterail/vuelidate#38]
From what I can tell there are no options to control when a validation is triggered and the out of the box implementation is to fire on each key press. There are pro's and con's to this and it would be good to see some alternatives.

A great article that looks at this issue is at [https://uxdesign.cc/forms-need-validation-2ecbccbacea1](https://uxdesign.cc/forms-need-validation-2ecbccbacea1) with the trigger specific content at [https://uxdesign.cc/forms-need-validation-2ecbccbacea1#e661](https://uxdesign.cc/forms-need-validation-2ecbccbacea1#e661)

I like the idea of using several triggers that will fire validation if any trigger is hit.

- After x milliseconds from the first keypress
- After a configured number of keys entered for a field
- When field onblur fired
- On key press when previously valid but now invalid

**Comment by Frizi** [comment]
What is your specific usecase?

The general idea of when to display the error relies on `$dirty` flag, and that one is totally controlled by the user. You can hook up any event or logic you want here.

Validators alone are simply functions from value/state to boolean validity (optionally in Promise). You need that logic to be able to always tell if your data is valid. That way it stays simple and consistent, while `$dirty` is taking care of conditional rendering. You don't have to take any special care of "unknown validity" state, because there is no such thing.

**Comment by roryprimrose** [comment]
Is there any doco about how to control when the validators are evaluated so that I can add different triggers to set ```$dirty```?

**Comment by Frizi** [comment]
Yes. Check age field in the first example.

**Comment by Gr33nbl00d** [comment]
i wrote some java swing validation framework in the past and i hope i can help to improve this framework. It looks promising from my point of view.. The different validation trigger types will just help partly. I called all components which can display an validation error as "Markers".

You often have at least 2 type of markers:
Live Markers (for example a red dot, or a label which is getting red or a red border).

Manual/Delayed Markers: Often you want to display a list of problems on top of the form. Maybe this list will also change the layout of the page if it is changing. You might want to show also some text next to some textfield. What you dont want is that these text/list of text is changing constantly while you are typing, 

Only reason i can imagine to change validation to be time triggered or delayed is that it could improve performance.

i would rather suggest to make some different functions or variables where you could delay the marker itself to give an example:

//show this text only if the value is for 5 seconds invalid
`
<span v-if="$v.name.$invalidsinceSeconds==5">User or Password Wrong</span>
`

I also have some requirement:
I have a button which will trigger a login function:

`<button @click="login"/>

login: function () {
  $v,$validate();         // instead of $v.$touch();
  if($v.$invalid==false)
  {
         -> send request to loginservice
   }
}`

i would like to show this text only after the user clicked on loginbutton.
this could be done like this:

`
<span v-if="$v.name.$invalidOnManualValidate==5">Username contains invalid chars</span>


What do you think?
`

**Comment by Frizi** [comment]
@Gr33nbl00d I can't imagine any situation when you would need more that one $dirty behaviour at a time on a single field. Implementing more complex "markers" are just a matter of writing a single function.

Let's for example do a simple `invalidFor5Seconds`:
```html
<input v-model="value" @input="dirty5sec($v.value)">
```

```javascript
const timeouts = new WeakMap()
const dirty5sec = (v) => {
  v.$reset()
  const last = timeouts.get(v)
  if(last) clearTimeout(last)
  if (v.$invalid) timeouts.set(v, setTimeout(v.$touch, 5000))
}
```

WeakMap could be avoided in many ways, but it's simplifies the example greatly.
