### ISSUE TITLE
Enter the page will automatically do a check

### ISSUE THREAD

**Issue by XuXiaoGH** [monterail/vuelidate#40]
Hello, I am a novice just use vuelidate, I have a doubt, the use of @blur, just enter the page will automatically do a check. I would like to ask what configuration can be entered in the first page of the time do not check it.

Here is my code.

Looking forward to your reply. Thank you!!!

### template
```
<input type="text"  v-model.trim="mobile" @blur="$v.mobile.$touch()">
<span v-if="!$v.mobile.check">mobile have problem</span>
```
### script
```
export default{
        name: 'login',
        data() {
            return {
                mobile:''
            };
        },
        validations: {
            mobile: {
                check:function (value) {
                    if(!(/^1[34578]\d{9}$/.test(value))){
                        console.log('mobile have problem');
                        return false;
                    }
                    return true;
                }
            },
        },
```

**Comment by pczarn** [comment]
To fix your issue, change the second line of the template to
```html
<span v-if="$v.mobile.$error">mobile have problem</span>
```
Only the `$error` attribute is affected by calls to `$touch()` and `$reset()`. The attribute you tried is calculated directly from the results of validation methods. So is the `$invalid` attribute.

There's still another problem. Users of your website may click on your input, decide they do not want to write anything, and click on another input. Then, the `@blur` error will run and an error will appear. If you want to validate after something has been entered, you should replace the use of `@blur` with `@change`:
```html
<input type="text" v-model.trim="mobile" @change="$v.mobile.$touch()">
```
Now it should work perfectly.

**Comment by XuXiaoGH** [comment]
thanks @pczarn !!!
Maybe I did not describe it clearly.
I doubt the moment when I entered the page, automatically do @ blue calibration. I do not think so.

I just want to click on the input box, the loss of focus, then check.

After I do the test, adding this will automatically trigger the check. Removed after there is no problem.
`<span v-if="!$v.mobile.check">mobile have problem</span>`

So I made a change, to achieve the requirements. I've customized a flag bit : ‘isMobile’

## template
```
<input type="text"  v-model.trim="mobile" @blur="$v.mobile.$touch()">
<span v-if="!isMobile">mobile have problem</span>
```

## script
```
export default{
        name: 'login',
        data() {
            return {
                mobile:'',
                isMobile:'true'
            };
        },
        validations: {
            mobile: {
                check:function (value) {
                    if(!(/^1[34578]\d{9}$/.test(value))){
                        console.log('mobile have problem');
                        return false;
                    }
                    return true;
                }
            },
        },
```

**Comment by pczarn** [comment]
Maybe you mean after entering the page you see `'mobile have problem'` in the console, which means a check runs, but you don't expect a check. Yes, it runs the code for validation when the component is created and every time the input changes. It works like this:

* you first enter the page
* the `check` function runs
* now, `mobile` is `''`
  * and `$v.mobile.check` is true, because an empty mobile is correct
  * and `$v.mobile.$invalid` is true, because an empty mobile is _incorrect_
  * and `$v.mobile.$dirty` is false, because the input was not touched
  * and `$v.mobile.$error` is false, because `$v.mobile` is not dirty
* you click on the input box
* you lose focus
  * `$v.mobile.$touch()` is called
  * now, `$v.mobile.$dirty` is true
* `mobile` didn't change
  * so `$v.mobile.check` and `$v.mobile.$invalid` are still the same
  * and `$v.mobile.$error` is true, because `$v.mobile` is dirty and invalid

So don't worry about the check function, it just does a test for an empty mobile number, but it does that test as soon as possible, before you touch the input box. Put this in the template
```html
<span v-if="$v.mobile.$error">mobile have problem</span>
```

**Comment by alexandrustefan** [comment]
Hi,

I have kind of the same problem but with the 'required' validation, whenever the component is displayed the validation runs, and it marks all the fields as invalid, because all of them are required, as for user experience there should be an option to prevent auto-validation, and bind it only to the specified event.

Example template : 

`<div class="uk-form-controls">
        <input v-bind:class="{ 'uk-form-danger': $v.email.$error }"
               v-model="email" v-on:input="$v.email.$touch()"
               class="uk-input" id="email" type="text"
               placeholder="email@email.com">
        <span v-if="!$v.email.email" class="uk-text-danger uk-margin-small">Invalid email</span>
        <span v-if="!$v.email.required" class="uk-text-danger uk-margin-small">Email is mandatory</span>

      </div>`

The `!$v.email.required` is being evaluated to false when I access the page for the first time (without even touching the input), displaying the "Email is mandatory" error. 

Checking for `$v.email.error` is not a good thing when you want to display several messages for each type of validation.

One more thing, I've seen that on docs page, that when I access the page for the first time, the 'required' is 'true', which I actually want to achieve myself, but don't know how.

**Comment by pczarn** [comment]
@alexandrustefan One way is to display messages for each type of validation when `$error` is true, and none of them otherwise. (you may replace `$error` with `$dirty` here)
```html
<div class="uk-form-controls">
  <input v-bind:class="{ 'uk-form-danger': $v.email.$error }"
         v-model="email" v-on:input="$v.email.$touch()" class="uk-input"
         type="text" placeholder="email@email.com">
  <div v-if="$v.email.$error">
    <span v-if="!$v.email.email" class="uk-text-danger uk-margin-small">Invalid email</span>
    <span v-if="!$v.email.required" class="uk-text-danger uk-margin-small">Email is mandatory</span>
   </div>
</div>
```
An equivalent solution is to add checks for `$dirty` in each condition for messages. After all, `$error` is equivalent to `$invalid && $dirty`.
```html
<div class="uk-form-controls">
  <input v-bind:class="{ 'uk-form-danger': $v.email.$error }"
         v-model="email" v-on:input="$v.email.$touch()" class="uk-input"
         type="text" placeholder="email@email.com">
  <span v-if="!$v.email.email && $v.email.$dirty" class="uk-text-danger uk-margin-small">Invalid email</span>
  <span v-if="!$v.email.required && $v.email.$dirty" class="uk-text-danger uk-margin-small">Email is mandatory</span>
</div>
```
When I enter the docs, all `required` fields are `false`, except for two of them, where `true` makes sense.
