### ISSUE TITLE
Add $success value which is the opposite of $error

### ISSUE THREAD

**Issue by johnnynotsolucky** [monterail/vuelidate#44]
It's easy enough to calculate the value, but it would be cool if it was already computed.

Use case:

If there is a requirement to display the validity of input whether its valid or invalid; additional logic needs to be written to determine whether the value is dirty and valid:

```
<template>
  <input v-model="value" :class="{ success, error: $v.value.$error }" />
</template>

...
computed: {
  valid() {
    return this.$v.value.$dirty ? !this.$v.value.$invalid : null
  },
  success() {
    return this.valid === true
  },
},
```

Whereas if it were computed for us:

```
<template>
  <input v-model="value :class="{ success: $v.value.$success, $v.error: value.$error }" />
</template>
```

An example where it could be useful would be for a password strength validator - `$success` would indicate that the password is strong enough.

I'd love to submit a pull request if this is a viable enhancement.

**Comment by Frizi** [comment]
Hi!
I'd like to limit the number of those special values for a few reasons. First, to keep things simple for beginners, second to keep it readable. But I definitely can see the benefit you present here.

If your use case is local to a specific component, you can just create an method, like
```javascript
isSuccess(v) {
   return !v.$invalid && v.$dirty
}
```
So you can then use it in similar way to what you proposed.
```html
<input v-model="value :class="{ success: isSuccess($v.value), $v.error: value.$error }" />
```

For anything more global, this could be imported per module or adapted as a mixin.

You could also try your luck by adding validators to validate other validators. It should work (that's the princible behind validation groups), but I wouldn't recommend that because of lack of clarity and better existing options.

Alternatively, a possible extension point could be added to Vuelidate to allow adding custom computed values into the validation. You have to keep in mind though that inner vm instance is not exactly the same as exposed object. There is one more proxy object in play and it is actually necessary to avoid name collisions or for async validators to work. I wouldn't  like to expose internals to public API.

**Comment by johnnynotsolucky** [comment]
Thanks for the feedback! 

It never crossed my mind to use a mixin, that should work perfectly.

I think the last point might be overkill; exposing internals to the public API might make it harder to make non-breaking changes to Vuelidate in the future, and like you said, the API currently is simple and logical.

**Comment by cypherix93** [comment]
Please reconsider this request, as it will be very beneficial when using Vuelidate with libraries such as Bootstrap, that has [distinct validation states for form inputs](https://getbootstrap.com/docs/3.3/css/#forms-control-validation). Having a `$success` shortcut would be immensely useful.

**Comment by jpickwell** [comment]
Why not use `!$v.value.$error`?
