### ISSUE TITLE
$dirty Will not automatically become true

### ISSUE THREAD

**Issue by XuCe** [monterail/vuelidate#67]
$dirty Will not automatically become true
must use $touch to change

**Comment by 38elements** [comment]
According to the [document](https://monterail.github.io/vuelidate/#sub-v-values),
I think the behavior that `$dirty` does not automatically become true without using `$touch` is correct.

**Comment by shentao** [comment]
Just like @38elements said – you have to manually trigger the `$dirty` flag using `$touch`.

**Comment by mkoryak** [comment]
just curious, what is the reasoning behind that decision?  It seems like it introduces a lot of boilerplate code

**Comment by ecmel** [comment]
Dirty should come from user interface interaction, that is the correct behavior IMO.

**Comment by shentao** [comment]
That is true if think about validations only in terms of simple forms, but that is not always the case. The `$dirty` flag is just a helper and triggering it manually is actually a design decision. It can be used in different context. Sometimes it’s a `dirty` flag, the other time it can be a `submitted` flag. 

Why? Because we didn’t want to assume when the dirty flag should be triggered. Also, the only way we could do this without introducing some custom directives is probably on data change (inside computed values that the validators really are), which would be the equivalent of using `@input` on a text input. This is not very flexible. If we decided to use a directive then it wouldn’t be shorter than using the `$touch()` method. It would also require the registration of a directive before even doing so.

**Comment by mkoryak** [comment]
I like that reasoning. I actually wrote some really weird custom validation logic where I was validating a hidden input being set by multiple visible inputs, and the flexibility this added was really useful. It is still interesting to hear _why_ you decided to do this.

**Comment by shentao** [comment]
@mkoryak happy to hear this.

Vuelidate is loosely based on my custom solution for a large editable-datatable component that has different models and validations for each cell. The cells can also be different input types: text, number, vue-multiselect, datepicker. I also liked the idea of Ember-models. 

The validation rules there get really complex for example, we have to compare start/end dates not just between each other, but also check if the group of records provides a full coverage for a date range specified in the container. And that none of the record dates overlap each other.
Group – because depending on some information (category, code, location etc.) the records are grouped so they don’t collide.

However, some fields can be empty (for example, don’t have a location set), which means they are a default group and the more specified (with locations) are treated as exceptions. In this case, the collection of records doesn’t have to provide a full coverage if a default group already covers the date range.

That’s for dates. A record also has other fields that have different kinds of validations and all this has to be auto-saved to the server.

**Comment by Frizi** [comment]
@mkoryak: @shentao already provided some insights on origin of this idea, but some decisions were made later when we decided to make it a standalone thing. $dirty flag behaviour was one of them. Originally it was supposed to be a directive that would do as much as possibly automatically, but it turned out doing such is not really possible. So many components do stuff differently, and sometimes you simply need different behaviour. Going down the route taken by existing solution, you will find things like angular's `ng-model-options`, but it's just piling up complexity for no apparent reason. You will find more and more edge cases to solve. So, we took a step back. What we fundamentally want to do is to decide when the validation is becoming visible. The only functionality that can cover that fully is Vue's own excellent event system, and it's free in terms of implementation cost, allows you to do pretty much any magic you want. So we decided to make it as easy to use as possible instead of creating custom solutions. It turned out to work great 😄

That's one of the reasons Vuelidate is so small and has very minimal API surface. It's easier to use and learn that way, while leaving you the room for any custom logic you will ever need.

**Comment by AntonGrandizLubushko** [comment]
> $dirty Will not automatically become true
> must use $touch to change

And must use $reset() to set false, useful after getting OK response

**Comment by cocobuster** [comment]
I had a similar issue where anyDirty and Dirty didnt seem to update when I modified my input field... after reading the vuelidate doc example I realized that I was not using the proper object on v-model...

Lets say you have a props text that you want to link to an input
export default {
    props: {
      text: {
        type: String,
        default: ''
      },
   validations () {
      return {
        text: { required }
      }
    },
}


Dont do this:
 <input
    v-model="text"
    class="form-control"
    type="text"  
 >


Instead do this...  call the $model property from the $v object... and not the "text" from your Props or Data
 <input
    v-model="$v.text.$model"
    class="form-control"
    type="text"  
 >

 and anyDirty and Dirty will behave without calling touch()
I hope this help

**Comment by kdekooter** [comment]
What if I WANT my validation framework to take care of this transparently? What's the use of a required validation if the framework is not able to detect this state by itself?

Guess I am going to have to look for an alternative validation framework.

**Comment by dobromir-hristov** [comment]
> What if I WANT my validation framework to take care of this transparently? What's the use of a required validation if the framework is not able to detect this state by itself?
> 
> Guess I am going to have to look for an alternative validation framework.

Dude... You didn't even check the docs. We have autoDirty now, it just works...no need for $model if you don't want to.

**Comment by kdekooter** [comment]
That sounds like a good solution! Too bad it is not in the docs yet... 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/508983/111136491-1800a100-857e-11eb-9aed-106d32d23b38.png">

The only thing I could find was this thread explaining why _not_ having an auto-dirty feature was a great idea.

**Comment by shentao** [comment]
@kdekooter Are you sure you are looking at the correct docs for version 2.0? https://vuelidate-next.netlify.app/guide.html#setting-dirty-state-with-autodirty

**Comment by kdekooter** [comment]
I am looking at the docs for the current 0.7.6 version.

**Comment by shentao** [comment]
Then `$autoDirty` is not available for that version nor will it ever be added. You will need to update. 
But before you start "threatening" to use another library, I heard this one is pretty good https://vee-validate.logaretm.com/v3/. 
Bye 👋

**Comment by kdekooter** [comment]
My apologies about the "threat".

I am afraid my client is not going to be happy to upgrade to an alpha version of a library that also requires the Vue composition API... So I guess we will have to implement "manualDirty" for now.

**Comment by shentao** [comment]
Sorry to hear that. If that helps, I’m using both in a production app for a few months without issues.
