### ISSUE TITLE
Question: Way to trigger validation on submit instead of keyup?

### ISSUE THREAD

**Issue by emjimadhu** [monterail/vuelidate#83]
Is it possible to do validation on submit only, instead of key up? im new vue, if you already have this method, can you point me out?

**Comment by Frizi** [comment]
Yes, simply use `@submit="$v.$touch()"` on your form element.

**Comment by emjimadhu** [comment]
thank you.. I will try it,.

**Comment by izundo-viennv** [comment]
@Frizi But after submit, it will validate on key instead of validating on submit

**Comment by shentao** [comment]
@izundo-viennv The validation always happens in real-time whenever data changes. The `$touch` only triggers the `$dirty` state which in turn is required for `$error` to be true (`$error = $dirty && $invalid`).

**Comment by diakonovm** [comment]
> The validation always happens in real-time whenever data changes.

This should be optional. Arguably beneficial for an end user to receive real-time form validation, nonetheless, I would prefer this to be opt-in rather than the default behavior.

You say `$touch` only triggers the `$dirty` state, but in the following I am not calling `$touch` until submission yet still receive real-time form validation errors.

```html
<div class="o-input-field">
  <input
    v-model.trim="$v.form.email.$model"
    :class="{ 'o-input--error': $v.form.email.$error }"
    type="email"
    placeholder="E-mail"
    class="o-input"
    aria-label="email"
  >
  <div v-if="$v.form.email.$dirty">
    <div class="input-error" v-if="!$v.form.email.required">Email is required</div>
    <div class="input-error" v-if="!$v.form.email.minLength">Email must be 6 or more characters</div>
    <div class="input-error" v-if="!$v.form.email.maxLength">Email must be less than 64 characters</div>
  </div>
</div>
```

**Comment by shentao** [comment]
@diakonovm We agree! That’s why in the next Vuelidate major release (targeted at Vue 3.0), all validations are lazy by default. This means that unless you change the `$dirty` state yourself or let it be automatically tracked, none of the validators will execute. This also means that once you call `$reset` it will disable the validators from being executed.

As for your question – you’re using `$v.form.email.$model` proxy property (not a real ES proxy, just a proxy getter/setter). This allows vuelidate to automatically track whether you modify that property. You can instead just use `v-model="form.email"` and then call `$touch` yourself.

**Comment by diakonovm** [comment]
@shentao Thanks, works just as I want now.

**Comment by shentao** [comment]
Happy to hear that! 👍

**Comment by asologor** [comment]
@shentao 

> You can instead just use `v-model="form.email"` and then call `$touch` yourself.

And I had to search through github issues to find this because your docs don't actually clarify such a common use case.
Anyway, after the first `$touch()` call the form starts validating on every keypress as before. Far from perfect.

**Comment by shentao** [comment]
@asologor what’s wrong with instant feedback for your users once they tried to submit an invalid form?

**Comment by asologor** [comment]
@shentao ok, after the first form submission it's fine, though it may not comply with some UX decisions.

As for instant field validation before the first submission, I know there are some studies that prove that immediate error feedback provides the worst user experience. Users tend to spend more time on such forms.

**Comment by dobromir-hristov** [comment]
@asologor hey, Vuelidate co-author here, how so you want Vuelidate to behave for you? What do you think is a better model?

**Comment by shentao** [comment]
@asologor I agree! That’s why you can use the `$touch` method to trigger the dirty state, so users don’t see the errors upfront (when you use `$error` instead of `$invalid` to show the errors). So when they first fill in the form, the errors are not displayed (though you can make it so that specific fields are turned dirty with for example `@blur="$v.propertyName.$touch()"`. Or if you would prefer to wait for the whole form, then run the global `$v.$touch()` on the Submit button. Then all the fields will be considered dirty. If you would like to reset the dirty state when someone focuses on a specific input, you can use `@focus="$v.propertyName.$reset()"`. 

So as you can see, you have a lot of control when it comes to when to show the errors, whether the feedback should be instant or not. It might require a bit more code, but that’s the price to pay for all the control.

As a note: in the next Vuelidate version (currently in alpha), all validators are lazy (not executed) unless the property is `$dirty`.

**Comment by asologor** [comment]
@dobromir-hristov  @shentao pretty clear explanation, thank you! But as you have mentioned, such control requires some boilerplate code that form validation libraries are supposed to kill. I think it would be much easier if we had some global validation configuration per component. For example, Formik has `validateOnBlur ` and `validateOnChange` props on its `Form` component.

It's just my personal opinion though.

**Comment by shentao** [comment]
Yeah! Those are also good ideas. Keep note though, that we don’t ship any components here so that everyone could build their own form components the way they want it. Vuelidate for example, is fully capable of validating your computed properties where for example, you don’t care about specific inputs, but only have to validate their combined output. Hence you can even set up validations on vuex getters or state if you need. This is often a case where component/template-centric form libraries struggle. Is it for everyone? Probably not! When I first built it, I had this very case where I had a table where:
* every cell needed their own validations
* different cells needed to be compared with each other
* every row had to be validated against other rows
* the whole table had to be validated against a certain context

Those are cases where the granular control and not that many assumptions are helpful.

Then again, you don’t have forms like this every day... That’s why there are some helpers. You can use `v-model="$v.propertyName.$model"` to `$touch` a property automatically when it changes.

The new version of Vuelidate comes with multiple more improvements like for example built-in error messages and things like `$autoDirty: true` param that you can pass to selected rules so they turn `$dirty` when their value changes. 

As for the `validateOnBlur` technique – I think you could build a Form component that would do just that. A bit more work, but then you control how everything happens.

**Comment by dobromir-hristov** [comment]
We could provide these at a later phase as optional components :) let's get the library to a stable State for vue ;)

**Comment by jcpc91** [comment]
"Hello, I am writing this in 2024. I have the following simple requirement: validate the form only when the user presses the submit button. I made a simple form for testing where I have a method called `customValidator()` that makes a call to a REST API, but the problem is that once the user pressed the submit button and if the user starts typing, the API call is made with every keystroke. I have already tried using the lazy property, but I might be missing something. Could someone point out what I need to ensure that all form validations occur when the submit button is pressed? Thank you."

```
<template>
  <form @submit.prevent="submitForm">
    <h1>kardex index</h1>
    <div>
      <label for="nombre">Nombre:</label>
      <input id="nombre" v-model="formData.nombre" @blur="$v.nombre.$touch" />
      <span v-if="$v.nombre.$error">{{ $v.nombre }}</span>
    </div>
    
    <div>
      <label for="apellidoPaterno">Apellido Paterno:</label>
      <input id="apellidoPaterno" v-model="formData.apellidoPaterno" />
      <span v-if="$v.apellidoPaterno.$error">El apellido paterno es requerido.</span>
    </div>
    
    <div>
      <label for="apellidoMaterno">Apellido Materno:</label>
      <input id="apellidoMaterno" v-model="formData.apellidoMaterno" />
      <span v-if="$v.apellidoMaterno.$error">El apellido materno es requerido.</span>
    </div>
    
    <div>
      <label for="edad">Edad:</label>
      <input type="number" id="edad" v-model="formData.edad" />
      <span v-if="$v.edad.$error">
        La edad es requerida y debe ser mayor de 18 años.
      </span>
    </div>
    
    <button type="submit">Enviar</button>
  </form>
</template>
<script setup>
import { ref } from "vue";
import { useVuelidate } from "@vuelidate/core"
import {TestApi} from '../services/index.js'

const formData = ref({})
const rules = {
      
        nombre: { customvalidator, $lazy: true},
        apellidoPaterno: {  },
        apellidoMaterno: {  },
        edad: { },
      
    };
const $v = useVuelidate(rules, formData)

async function submitForm() {
  const isFormCorrect = await $v.value.$validate()
    console.log('invalido', $v.value.$invalid)
  if (!isFormCorrect) return
  console.log('submitform ok')
}

async function customvalidator(value) {
  if (value){
    const v = await TestApi(value)
    console.log('api', v)
    return v
  }
  return true
}
</script>
```
