### ISSUE TITLE
version of $dirty that is true if any children have been changed

### ISSUE THREAD

**Issue by michaelsorich** [monterail/vuelidate#84]
I would also like to have a value that is similar to $dirty with the difference being that it is true if **any** (rather than all) of the children are $dirty. The purpose to make it easy to track if there have been any changes in the overall form or a specific section of the form - e.g. certain actions will be available if even only one value has changed.

I am just not sure how best to do this. I understand that $dirty is a computed value, so preferably I would like to add a complementary computed value to $dirty (e.g. $anydirty) to be access in a similar manner to the $dirty value. If anyone in the know has some guidance on the best way to achieve this it would be greatly appreciated.

**Comment by Frizi** [comment]
You can kinda do this by registering a mixin, but that's a hack. I don't want to add this kind of specific features to the vuelidate core, but extending it would be a neat feature. I'm not sure though about how to document that and what would be the API surface. Allowing mixins would prevent me from refactoring away the usage of `new Vue` internally, which I would like to reserve as an option.

Any ideas?

**Comment by Frizi** [comment]
@michaelsorich Have you done anything with this requirement on your end? I'd like to have a feedback if that's still useful thing to have.

Having `$anyDirty` is a super easy thing to implement, but I'm worried about it being very confusing to newcomers. Additional thing to understand.

**Comment by exnihilo-creatio** [comment]
@michaelsorich It is a useful feature to have. Right now I'm using the $v.$touch() on every input in order to make a disabled button enabled on a single change within a single form. I do not know any other method of achieving this, except for testing each fields validity on every form, which in a form of 20 fields gets tiresome. It was also the first essential feature I noticed missing that I ran into within the first few hours. 

Example use case: you want to edit a certain single field inside a form, and the save button only enables if there is a change inside the form. This is currently only possible by having your own computed on the form that checks the $dirty property for each individual field, i.e. field1.$dirty || field2.$dirty || ....

**Comment by codylandry** [comment]
I'd like to add a vote for this feature.  I was hoping to show a confirmation modal if the user tries to cancel a form once they've touched any field on it.  My intuition was that $dirty would be true if any child was $dirty, but obviously was wrong.  Doesn't that make sense though? I feel like there are more use cases for checking whether any field is dirty than all of them.

**Comment by michaelsorich** [comment]
@Frizi - From a brief attempt to build upon some of the existing vuelidate
code it seemed that the dirty property in vuelidate (including all the
associated code for propagating the flag between children) appeared to be
too focused on the specific use case of detecting that all fields have been
touched. It seemed easier to write the code from scratch than extend
vuelidate code for this purpose. Thus I used vuelidate to validate the data
but my own custom code to track changes.

**Comment by garhbod** [comment]
Like what @codylandry, shouldn't a `$dirty` child make the parent/ancestors `$dirty` also?

And by default I'm not sure `$dirty` should propagate downwards through the children/descendants.

Maybe adding a param to `$touch()` is the answer we are looking for here.

`$touch(true)` would propogate the `$dirty` upwards through the parent/ancestors.

or adding both directions as two params.

`$touch(propagateToAncestors = false, propagateToDescendants = true)`

**Comment by Frizi** [comment]
@garhbod Dirtyness is reactive, not imperative. That means we can't parametrize that on "sender" side (`$touch`), but on "receiver" instead (`$dirty` flag).

The easiest approach would be to create new property that is true when *any* instead of *all* children are flagged. Let's call it `$anyDirty` for now (if you have better name, please suggest).

But now we have another problem. There is `$error` property that uses `$dirty` instead of `$anyDirty`. Now this preference is arbitrary. Should we also have another property for that?

**Comment by codylandry** [comment]
Personally,  I believe you should simply change the behavior of $dirty itself and add an $allDirty.  $error would still base itself on $dirty.   I'd bet that most aren't relying on this behavior and are in fact writing the code to check for any dirty field as a work around. You're still below a 1.0 release so I think this is a acceptable change.  However, this is just my opinion and I could be totally off base.

**Comment by garhbod** [comment]
What down side is there to having the existing `$dirty` changed to work the same as `$invalid` in that if a child is `$dirty` than a parent must also be `$dirty`.

Making it simple to check `$v.$error` on a form submission to make sure there are no errors. Or check `$v.$dirty` to see if any unsaved changes exist.

**Comment by oldskool73** [comment]
hello, only been using this library for a couple of hours and liking it so far but wanted to +1 on what everyone is saying above, $dirty should be set in a parent if any child is dirty, that's the way I'd expect it to work (coming from Angular), and exactly the same behaviour as $invalid. 

And given that change, $error would also work 'as expected'. At the moment, if I have form object with nested validations and one nested item is invalid, its `$invalid=true` and `$error=true`, but in the parent its `$invalid=true` but `$error=false`, this seems inconsistent and I initially assumed it was a 🐛 

Seems like it might be just a one word change, `every` to `some` in the nestedKeys check?

If you want to keep the current checking and maintain backwards compatibility, perhaps it's an flag you can set on init, `Vuelidate.setDeepDirty(true)` or something to change the default behaviour?

**Comment by Frizi** [comment]
@garhbod What would you get from checking `$v.$error`? You should use `$v.$invalid` as your guard before submitting any form. `$error` is purely a visual feedback helper.

Having said that, i really see @oldskool73's argument here.
> but in the parent its $invalid=true but $error=false, this seems inconsistent

I imagine it might be confusing when you have multiple nested forms side by side.
Keep in mind that this is still a logical possible state, and even the default one more often than not. For example a required field not being touched yet will get you there, doesn't matter how we will propagate the `$dirty` flag. You should not rely on `$error` in your submission logic because of that.

> If you want to keep the current checking and maintain backwards compatibility, perhaps it's a flag you can set on init, Vuelidate.setDeepDirty(true) or something to change the default behaviour?

I'd like to avoid any global configuration. I'd like to preserve the ability to have current behaviour, but the "natural" way should be the default one. As @codylandry, Vuelidate is still below 1.0, so it's valid to change the API and just bump the minor to incidate breaking changes. I'd like to keep the changes minimal and trivially easy to migrate though.

So, my proposition here is to change the fields accordingly:
- current `$dirty` will become `$allDirty`
- current `$error` will become `$allError`
- new `$dirty` will have new behaviour as proposed, changing the logic from `every` to `some`
- new `$error` will be the equivalent of `$allError`, but based on new `$dirty` flag

This change will have to be documented in the docs with clear migration process presented (that should be simple enough).

Related observation:
- current `$pending` flag is based on `some`. It should suit the model well, but is there any valid usecase `$allPending`?

**Comment by codylandry** [comment]
> For example a required field not being touched yet will get you there, doesn't matter how we will propagate the $dirty flag. You should not rely on $error in your submission logic because of that.

Right, I agree that we shouldn't use $dirty for submission, but we're displaying some error messages based on the value of $dirty on the parent of a collection of objects, which is what spurred my input.  

> I'd like to avoid any global configuration. I'd like to preserve the ability to have current behaviour, but the "natural" way should be the default one.

Agree as well.

> 
> So, my proposition here is to change the fields accordingly:
> 
> current $dirty will become $allDirty
> current $error will become $allError
> new $dirty will have new behaviour as proposed, changing the logic from every to some
> new $error will be the equivalent of $allError, but based on new $dirty flag

This sounds perfect to me.

> current $pending flag is based on some. It should suit the model well, but is there any valid usecase $allPending?

I can't think of any reason for it myself, although I'm sure somebody could come up with one.  If nothing else, having a consistent set of variables is probably worthwhile.

**Comment by Webifi** [comment]
> So, my proposition here is to change the fields accordingly:
> 
> current $dirty will become $allDirty
> current $error will become $allError
> new $dirty will have new behaviour as proposed, changing the logic from every to some

Perfect!

> new $error will be the equivalent of $allError, but based on new $dirty flag

A little confused by this.

**Comment by Codermar** [comment]
What's the status of this proposed change? Is it coming up on versions beyond 0.6.1?
It seems very difficult at this time to control the validity of a form if it involves collections or nested collections.

**Comment by qarthandgi** [comment]
Is there any update on this proposed feature?

**Comment by pomodoro-timer** [comment]
Just started using Vuelidate, great package. I agree, the default form level $dirty should be "any" child that is dirty and not "all" children dirty.

**Comment by kanethal** [comment]
Is there a recommended method for triggering a dirty state when any component of a form is touched? I'm not sure setting an event on every form input is strictly dry. If that's the intended method then so be it.

**Comment by lobo-tuerto** [comment]
@kanethal Good question. This issue has been open for a long time, hopefully we will hear from the maintainers soon.

**Comment by SzNagyMisu** [comment]
I have read myself through this conversation and still stuck at naming. I think, in a case of a `form`, _dirty_ means that **any** of its fields is _dirty_. (I wanted to use this on a complex search form, where the submit button is disabled as long as the user dirties at least one field.)

I understand that a `form` can have `invalid: true` and `error: false`, and error comes from `invalid && dirty`. But that doesn't change anything on what _dirty_ means.

Take the following example:

We have a form with two fields (`name` and `email` for example), both required. If there is an error in filling them, we show some error message below the field, and if there is an error filling the form, we show some general hint, like _"There is a problem in the form, see error messages"_ and a message like _"Good, so far"_ if there is no error. Now, if `name` field is filled correctly, it is _dirty_ and _valid_, the `email` field on the other hand is _untouched_ and _invalid_. So if _dirty_ was propagated to the form, it would show the error message - that is why it uses `all` instead of `some`, if I understood well... But if there is an error in the `name` field but `email` is still _untouched_, the user will see the error under `name` field **and** the general hint _"Good, so far"_.

My example may seem a bit unnatural, but the point is that I do not think it a good idea to flag a form _dirty_ only if all of its fields are dirty.

My suggestion would be to propagate the error flag from the children: **a form should have `$error: true` if any of its fields has `$error: true`**, and not if it is _invalid_ and _dirty_.

Anything I did not take into account?

**Comment by codylandry** [comment]
I completely agree.

**Comment by garhbod** [comment]
@SzNagyMisu If `$dirty` is propagated as you and many others have suggested than `$error` will automatically propagate along with it.

I don't get why this is still an issue. What negatives are there to propagate `$dirty`?

**Comment by SzNagyMisu** [comment]
Also I would like to add that the DOC [here](https://monterail.github.io/vuelidate/#sub-data-nesting) says:

> Parent validator errors out when any of its children reports an error.

Which is kind of the behavior I would expect, but it doesn't work even with the example provided.

**Comment by BenoitRanque** [comment]
+1 on what all said here. Knowing that _a_ field has been touched is a lot more useful than knowing _all_ fields have been touched. Example:

I have a form used to edit a record. I set $dirty on each field upon `@blur` (or `@change`). If the user tries to close the form, I check if form is dirty and if it is, I ask for confirmation "all changes will be lost"

I'm not sure what the use case is for the current implementation of $dirty

**Comment by detinho** [comment]
+1 If pull request adds at least one test.

**Comment by garhbod** [comment]
What happened to @Frizi  propositions of `$allDirty` for replacing the current `$dirty` rather than creating the `$anyDirty`?

**Comment by rhymes** [comment]
@garhbod I think they decided not to risk breaking existing code. See https://github.com/monterail/vuelidate/pull/289#issuecomment-390584851
